<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="13610" started-at="2020-01-15T22:31:49 BRT" finished-at="2020-01-15T22:32:02 BRT">
    <groups>
    </groups>
    <test name="Default test" duration-ms="13610" started-at="2020-01-15T22:31:49 BRT" finished-at="2020-01-15T22:32:02 BRT">
      <class name="br.com.rsinet.hub_tdd.falhas.CadastroFalha">
        <test-method status="PASS" signature="inicio()[pri:0, instance:br.com.rsinet.hub_tdd.falhas.CadastroFalha@4973813a]" name="inicio" is-config="true" duration-ms="5030" started-at="2020-01-15T22:31:49 BRT" finished-at="2020-01-15T22:31:54 BRT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- inicio -->
        <test-method status="FAIL" signature="cadastro()[pri:0, instance:br.com.rsinet.hub_tdd.falhas.CadastroFalha@4973813a]" name="cadastro" duration-ms="7016" started-at="2020-01-15T22:31:54 BRT" finished-at="2020-01-15T22:32:01 BRT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[A senha nao e a mesma! did not expect to find [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: A senha nao e a mesma! did not expect to find [false] but found [true]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertFalse(Assert.java:65)
at br.com.rsinet.hub_tdd.falhas.CadastroFalha.cadastro(CadastroFalha.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cadastro -->
        <test-method status="PASS" signature="fim()[pri:0, instance:br.com.rsinet.hub_tdd.falhas.CadastroFalha@4973813a]" name="fim" is-config="true" duration-ms="1518" started-at="2020-01-15T22:32:01 BRT" finished-at="2020-01-15T22:32:02 BRT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fim -->
      </class> <!-- br.com.rsinet.hub_tdd.falhas.CadastroFalha -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
